[build]
  functions = "netlify/functions"
  publish = "public" # This directory might need to be created or adjusted if you don't have a specific build output

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["*.html", "*.css", "*.js", "models/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
